# frozen_string_literal: true

source 'https://rubygems.org'

gemspec

gem 'json'
gem 'rack'
gem 'rake', '~> 12.3'
gem 'rspec', '~> 3.0'
gem "sinatra", "~> 2.1.0"
gem 'uuid'
gem "webrick"

gem "webrat", :group => :test

gem "rubocop", :group => :development
